// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxvxyXJdl4gSWYbhmmokI1849pNjsRYUE',
    appId: '1:879112790331:web:3085bf34fae2388591d71e',
    messagingSenderId: '879112790331',
    projectId: 'shopsm-3254e',
    authDomain: 'shopsm-3254e.firebaseapp.com',
    databaseURL: 'https://shopsm-3254e.firebaseio.com',
    storageBucket: 'shopsm-3254e.appspot.com',
    measurementId: 'G-9KSGTQSQR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgb8M122ri8E48D3TCFVAM9jH601Y9DeM',
    appId: '1:879112790331:android:b299d57a8113d8ea',
    messagingSenderId: '879112790331',
    projectId: 'shopsm-3254e',
    databaseURL: 'https://shopsm-3254e.firebaseio.com',
    storageBucket: 'shopsm-3254e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJigg1jvcZKnKsDgCcvCr1wCRfSRKorD0',
    appId: '1:879112790331:ios:4711a9efc9ce174c',
    messagingSenderId: '879112790331',
    projectId: 'shopsm-3254e',
    databaseURL: 'https://shopsm-3254e.firebaseio.com',
    storageBucket: 'shopsm-3254e.appspot.com',
    androidClientId: '879112790331-0akopdhak259r36pkfpvea2pjtv7pnk1.apps.googleusercontent.com',
    iosClientId: '879112790331-hhr4jfah3tikr9o8mvrsb2bcaielqdd5.apps.googleusercontent.com',
    iosBundleId: 'com.omnichannel.shopSm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJigg1jvcZKnKsDgCcvCr1wCRfSRKorD0',
    appId: '1:879112790331:ios:f7eee70a3d6bc32e91d71e',
    messagingSenderId: '879112790331',
    projectId: 'shopsm-3254e',
    databaseURL: 'https://shopsm-3254e.firebaseio.com',
    storageBucket: 'shopsm-3254e.appspot.com',
    androidClientId: '879112790331-0akopdhak259r36pkfpvea2pjtv7pnk1.apps.googleusercontent.com',
    iosClientId: '879112790331-lf19nlfg68r317vm05e7pcorgm928723.apps.googleusercontent.com',
    iosBundleId: 'com.omnichannel.shopSm.RunnerTests',
  );
}
